this work?

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -28,7 +28,10 @@ jobs:
           commit=$(lookup_latest_tag)
           charts_dir="helm-chart"
 
-          git diff --find-renames --name-only "$commit" -- "$charts_dir"
+          first=$(git diff --find-renames --name-only "$commit")
+          echo "CHANGED_FIRST=$first"
+          second=$(git diff --find-renames --name-only "$commit" -- "$charts_dir")
+          echo "SECOND=$second"
           changed_files=$(git diff --find-renames --name-only "$commit" -- "$charts_dir")
           echo "CHANGED_FILES=$changed_files"
 
@@ -41,7 +44,20 @@ jobs:
           fields="1-${depth}"
           echo "FIELDS=$fields"
 
-          cut -d '/' -f "$fields" <<< "$changed_files" | uniq
+          filter_charts() {
+              while read -r chart; do
+                  echo "CHART=$chart"
+                  [[ ! -d "$chart" ]] && continue
+                  local file="$chart/Chart.yaml"
+                  if [[ -f "$file" ]]; then
+                      echo "$chart"
+                  else
+                     echo "WARNING: $file is missing, assuming that '$chart' is not a Helm chart. Skipping." 1>&2
+                  fi
+              done
+          }
+
+          cut -d '/' -f "$fields" <<< "$changed_files" | uniq | filter_charts
 
       - uses: azure/setup-helm@v3
         with:
@@ -49,7 +65,11 @@ jobs:
           github-token: ${{ secrets.GITHUB_TOKEN }}
 
       - uses: helm/chart-releaser-action@v1.2.1
-        with:
-          charts_dir: helm-chart
         env:
           CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          if [[ -z "$(git diff --find-renames --name-only $(git rev-parse HEAD) -- helm-chart)" ]]; then
+            
+          fi
+
+
